version: 2.1

executors:
  python-playwright:
    docker:
      - image: mcr.microsoft.com/playwright/python:v1.38.0-focal

jobs:
  test-playwright:
    executor: python-playwright
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd src  # src 폴더로 이동
            pip install -r requirements.txt
            playwright install
      - run:
          name: Run Playwright test
          command: |
            cd src  # src 폴더로 이동
            python test_chatgpt.py
      - store_artifacts:  # 스크린샷 저장
          path: src/screenshot.png
      - run:
          name: Output Test Complete
          command: echo "Test Completed Successfully!"

workflows:
  version: 2
  test-and-store:
    jobs:
      - test-playwright
